name: Toril Snyen Marjala
favicon: null
layout_spectrum: 0.044380320934578776
typography_spectrum: 0.9820376813877374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#fbe1c5'
    - '#b5996d'
    - '#5b3a23'
    - '#866a43'
  brandStrength: 0.5578743841033429
  lightness: 0.07386005762964487
  saturation: 0.6630015568807721
  rhythmicContrast: 0.9169903760775924
purpose: []
